name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18.x
          cache: yarn
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn lint
      - run: yarn coverage
      - run: yarn test:ignored-in-coverage
