name: Gas

on:
  pull_request:
    paths:
      - '**.sol'
      - '**.yml'
      - '**.toml'
      - 'lib/**'
      - '.gitmodules'
      - '.gas-snapshot'
  push:
    branches:
      - main
    paths:
      - '**.sol'
      - '**.yml'
      - '**.toml'
      - 'lib/**'
      - '.gitmodules'
      - '.gas-snapshot'

env:
  FOUNDRY_PROFILE: ci

jobs:
  gas:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          persist-credentials: false

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          cache: yarn

      - run: yarn --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: nightly

      - name: Check gas snapshots
        run: forge snapshot --check
        # TODO: remove failure allowance once foundry migration is complete
        continue-on-error: true
