name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.sol'
  push:
    branches:
      - main
    paths:
      - '**.sol'

env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
        with:
          version: v1.3.5

      - name: Check Forge fmt
        run: forge fmt --check
        id: format
