name: Lint

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.sol'
      - '**.yml'
  push:
    branches:
      - main
    paths:
      - '**.sol'
      - '**.yml'

env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-node@v4
      - id: yarn-cache
        run: echo "dir=$(yarn cache dir)"  >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-
      - run: yarn --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Check formatting
        run: forge fmt --check
        # TODO: Remove the following line to allow the workflow to fail if the formatting is incorrect
        continue-on-error: true