name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.sol'
  push:
    branches:
      - main
    paths:
      - '**.sol'

env:
  FOUNDRY_PROFILE: ci

jobs:
  lint:
    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          persist-credentials: false

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de # v1.4.0
        with:
          version: nightly

      - name: Check Forge fmt
        run: forge fmt --check
        id: format
