name: Enforce Review Rules

on:
  pull_request:
    types: [opened, edited, synchronize]
    paths:
      - "src/contracts/**"

jobs:
  enforce-review-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false

    - name: Ensure required reviewers
      shell: bash
      id: ensure-reviewers
      run: |
        # Fetch approved and non-dismissed reviews of the PR
        REVIEWERS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                    "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER/reviews" \
                    | jq -r '[.[] | select(.state == "APPROVED" and .dismissed_at == null) | .user.login] | unique | .[]')

        if [ $? -ne 0 ]; then
          echo "Failed to fetch reviews"
          exit 1
        fi

        NUM_REVIEWERS=$(echo "$REVIEWERS" | wc -w)

        # Check review requirements
        if [ "$NUM_REVIEWERS" -lt 2 ]; then
          echo "Insufficient reviewers for src/contracts/ path. Required: 2 reviewers."
          echo "review_check_passed=false" >> $GITHUB_OUTPUT
          exit 1
        fi

        echo "review_check_passed=true" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        REPO: ${{ github.repository }}

    - name: Success message
      if: steps.ensure-reviewers.outputs.review_check_passed == 'true'
      run: echo "Review checks passed successfully!"
